### ISSUE TITLE
프로젝트 패키지 구조 정리

### ISSUE THREAD

**Issue by hyunzxn** [2022-Harmony/NewsCommunity-bFinal#229]
## 🎵 설명
- Why? 
: 패키지가 너무 많아져서 복잡해서 파악하기 어려움
<br>

- How?
: domain 패키지를 만들어 각자 맡은 기능에 관련된 패키지를 모아두고 공통으로 쓰는 패키지는 그대로 두는 방식으로 변경

## ✅ 이슈 만들 때 체크하셨나요?
- [x]  할당 (Assignees)
- [x]  라벨(Labels)
- [x]  프로젝트(Projects)

**Comment by enyo9rt** [comment]
와 라벨 색 너무 맘에 들어요~~
