### ISSUE TITLE
DTO (Request, Response) 활용

### ISSUE THREAD

**Issue by hyunzxn** [2022-Harmony/NewsCommunity-bFinal#44]
- ResponseDto 이용해서 API 리턴해주는 것으로 코드 통일

**Comment by enyo9rt** [comment]
여전히 필요한 부분이 있는 것 같아서 살펴보고 고치면 제가 클로즈 하겠읍니다...ㅜㅜ

**Comment by hyunzxn** [comment]
> 여전히 필요한 부분이 있는 것 같아서 살펴보고 고치면 제가 클로즈 하겠읍니다...ㅜㅜ

넵!
