### ISSUE TITLE
too many connections

### ISSUE THREAD

**Issue by enyo9rt** [2022-Harmony/NewsCommunity-bFinal#5]

**Comment by enyo9rt** [comment]
이게 무슨일이지? 하고보니 다들 로컬에서 커넥션을 유지시켜놓고 해제하지 않아 커넥션이 엄청 잡혀있는 상태였어요. (MSA 환경이어서 서비스마다 DB커넥션을 유지하기 때문에 한명당 6~7개 이상 잡아먹고 있음..) 베타 DB는 성능이 좋은 서버를 쓰지 않았기 때문에 버티지 못한것이었습니다.. ㅠㅠ

대충 이런상황을 해결하는 hikari 설정 코드 추가 by 영은nim

**Comment by choichanhyeok** [comment]
굿굿
